version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: esportefy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    expose:
      - 5432

  redis:
    image: "redis:alpine"
    container_name: esportefy_redis
    expose:
      - 6379

  web:
    build: .
    container_name: esportefy_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
