# Generated by Django 5.2.7 on 2026-03-27 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('bug', '🐛 Bug/Erro'), ('feature', '✨ Feature Request'), ('sugestao', '💡 Sugestão Geral'), ('outro', '❓ Outro')], default='sugestao', help_text='Tipo de feedback', max_length=20)),
                ('assunto', models.CharField(help_text='Título do feedback', max_length=200)),
                ('mensagem', models.TextField(help_text='Descrição detalhada do feedback')),
                ('email_contato', models.EmailField(blank=True, help_text='Email para contato (copiado de user.email se logado)', max_length=254)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False, help_text='Se o admin já viu')),
                ('respondido', models.BooleanField(default=False, help_text='Se foi respondido')),
                ('resposta', models.TextField(blank=True, help_text='Resposta do admin')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário que enviou o feedback. Null se anônimo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ('-data_criacao',),
            },
        ),
    ]
