# Generated by Django 5.2.6 on 2025-09-11 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esportes_preferidos', models.CharField(blank=True, choices=[('Futebol', 'Futebol'), ('Tenis', 'Tênis'), ('Volei', 'Vôlei'), ('Basquete', 'Basquete'), ('Outro', 'Outro')], max_length=100, null=True, verbose_name='Esporte Preferido')),
                ('nivel_habilidade', models.CharField(blank=True, choices=[('Iniciante', 'Iniciante'), ('Intermediario', 'Intermediário'), ('Avancado', 'Avançado'), ('Competitivo', 'Competitivo')], max_length=50, null=True, verbose_name='Nível de Habilidade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
