# Generated by Django 5.2.6 on 2025-09-11 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esportes_preferidos', models.CharField(blank=True, choices=[('Futebol', 'Futebol'), ('Tenis', 'Tênis'), ('Volei', 'Vôlei'), ('Basquete', 'Basquete'), ('Queimada', 'Queimada')], max_length=100, null=True, verbose_name='Esporte Preferido')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
