# Generated by Django 5.2.6 on 2025-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
    ]
