# Generated by Django 5.2.6 on 2025-09-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_perfil_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Sobre Mim'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='fotos_perfil/default.jpg', null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil'),
        ),
    ]
