# Generated by Django 5.2.6 on 2025-09-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_perfil_amigos_solicitacaoamizade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='bio',
            new_name='mini_bio',
        ),
        migrations.AddField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
    ]
