# Generated by Django 5.2.7 on 2026-03-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_rename_bio_perfil_mini_bio_perfil_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='mostrar_aniversario',
            field=models.BooleanField(default=True, verbose_name='Mostrar aniversário'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='mostrar_banner',
            field=models.BooleanField(default=True, verbose_name='Mostrar banner'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='mostrar_cidade',
            field=models.BooleanField(default=True, verbose_name='Mostrar cidade'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='mostrar_data_criacao',
            field=models.BooleanField(default=True, verbose_name='Mostrar data de criação'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='mostrar_idade',
            field=models.BooleanField(default=True, verbose_name='Mostrar idade'),
        ),
    ]
