# Generated by Django 5.2.6 on 2026-03-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0006_perfil_banner_perfil_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='mostrar_aniversario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='mostrar_banner',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='mostrar_cidade',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='mostrar_data_criacao',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='mostrar_idade',
        ),
        migrations.AddField(
            model_name='perfil',
            name='banner_position',
            field=models.CharField(blank=True, default='50% 50%', max_length=20, verbose_name='Posição do Banner'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners_perfil/', verbose_name='Banner do Perfil'),
        ),
    ]
