# Generated by ChatGPT on 2026-03-31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0007_remove_perfil_data_nascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('login_method', models.CharField(choices=[('password', 'Senha'), ('social', 'Social'), ('unknown', 'Desconhecido')], default='unknown', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Login',
                'verbose_name_plural': 'Eventos de Login',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_profile_public', models.BooleanField(default=True)),
                ('show_online_status', models.BooleanField(default=True)),
                ('allow_friend_requests', models.BooleanField(default=True)),
                ('two_factor_email_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Privacidade',
                'verbose_name_plural': 'Configurações de Privacidade',
            },
        ),
    ]
