# Generated by Django 5.2.6 on 2026-04-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0008_userprivacysettings_accountloginevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bairro_base',
            field=models.CharField(blank=True, choices=[('flamengo', 'Flamengo'), ('centro', 'Centro'), ('sao_jose', 'São José do Imbassaí'), ('itaipuacu', 'Itaipuaçu'), ('itaocaia', 'Itaocaia Valley'), ('parque_nanci', 'Parque Nanci'), ('guaratiba', 'Guaratiba'), ('barroco', 'Barroco'), ('caxito', 'Caxito'), ('mumbuca', 'Mumbuca'), ('bananal', 'Bananal'), ('inoã', 'Inoã'), ('itapeba', 'Itapeba')], max_length=50, null=True, verbose_name='Seu Bairro Principal'),
        ),
    ]
