# Generated by Django 5.2.6 on 2025-09-15 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título da Partida')),
                ('esporte', models.CharField(max_length=50, verbose_name='Esporte')),
                ('bairro', models.CharField(choices=[('flamengo', 'Flamengo'), ('centro', 'Centro'), ('sao_jose', 'São José do Imbassaí'), ('itaipuacu', 'Itaipuaçu'), ('itaocaia', 'Itaocaia Valley'), ('parque_nanci', 'Parque Nanci')], max_length=50, verbose_name='Bairro')),
                ('local', models.CharField(max_length=200, verbose_name='Local (Nome da quadra, rua, etc.)')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('jogadores_necessarios', models.PositiveIntegerField(verbose_name='Jogadores Necessários')),
                ('jogadores_confirmados', models.ManyToManyField(blank=True, related_name='partidas_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_organizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['data_hora'],
            },
        ),
    ]
