# Generated by Django 5.2.6 on 2025-09-15 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0002_avaliacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_fair_play', models.PositiveIntegerField(verbose_name='Nota de Fair Play (1 a 5)')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_jogador_recebidas', to=settings.AUTH_USER_MODEL)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_jogador_feitas', to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_jogador', to='partidas.partida')),
            ],
            options={
                'verbose_name': 'Avaliação de Jogador',
                'verbose_name_plural': 'Avaliações de Jogadores',
                'unique_together': {('partida', 'avaliador', 'avaliado')},
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoQuadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_quadra', models.PositiveIntegerField(verbose_name='Nota para a Quadra (1 a 5)')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_quadra_feitas', to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_quadra', to='partidas.partida')),
            ],
            options={
                'verbose_name': 'Avaliação da Quadra',
                'verbose_name_plural': 'Avaliações das Quadras',
                'unique_together': {('partida', 'avaliador')},
            },
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
