# Generated by Django 5.2.6 on 2025-09-16 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0003_avaliacaojogador_avaliacaoquadra_delete_avaliacao'),
        ('quadras', '0002_alter_quadra_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='local',
        ),
        migrations.AddField(
            model_name='partida',
            name='quadra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='quadras.quadra', verbose_name='Quadra'),
        ),
    ]
