# Generated by Django 5.2.6 on 2025-11-04 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0004_remove_partida_bairro_remove_partida_local_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Esporte',
                'verbose_name_plural': 'Esportes',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='partida',
            name='esporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidas.esporte', verbose_name='Esporte'),
        ),
    ]
