# Generated by Django 5.2.6 on 2026-03-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0003_comentario_partida'),
        ('partidas', '0005_esporte_alter_partida_esporte'),
    ]

    operations = [
    ]
