# Generated by Django 5.2.6 on 2026-04-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0007_comentariopartidalike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comentariopartidalike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='comentariopartida',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='comentariopartida',
            name='partida',
        ),
        migrations.RemoveField(
            model_name='comentariopartida',
            name='resposta_a',
        ),
        migrations.RemoveField(
            model_name='comentariopartidalike',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='comentariopartidalike',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CancelamentoPartida',
        ),
        migrations.DeleteModel(
            name='ComentarioPartida',
        ),
        migrations.DeleteModel(
            name='ComentarioPartidaLike',
        ),
    ]
