# Generated by Django 5.2.6 on 2026-04-02 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0008_remove_comentariopartida_autor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interesse', 'Interesse'), ('confirmado', 'Confirmado'), ('recusado', 'Recusado'), ('expirado', 'Expirado')], default='interesse', max_length=12, verbose_name='Status')),
                ('motivo_recusa', models.CharField(blank=True, max_length=255, verbose_name='Motivo de recusa')),
                ('observacao_recusa', models.TextField(blank=True, verbose_name='Observação opcional')),
                ('lembrete_24h_enviado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('recusado_em', models.DateTimeField(blank=True, null=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_rsvp', to=settings.AUTH_USER_MODEL, verbose_name='Jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='partidas.partida', verbose_name='Partida')),
            ],
            options={
                'verbose_name': 'RSVP de Partida',
                'verbose_name_plural': 'RSVPs de Partidas',
                'unique_together': {('partida', 'jogador')},
            },
        ),
        migrations.AddIndex(
            model_name='partidarsvp',
            index=models.Index(fields=['status', 'atualizado_em'], name='partidas_pa_status_9dc607_idx'),
        ),
        migrations.AddIndex(
            model_name='partidarsvp',
            index=models.Index(fields=['partida', 'status'], name='partidas_pa_partida_45fba7_idx'),
        ),
    ]