# Generated by Django 5.2.6 on 2026-04-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0009_partidarsvp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='partidarsvp',
            new_name='partidas_pa_status_9b29aa_idx',
            old_name='partidas_pa_status_9dc607_idx',
        ),
        migrations.RenameIndex(
            model_name='partidarsvp',
            new_name='partidas_pa_partida_617d83_idx',
            old_name='partidas_pa_partida_45fba7_idx',
        ),
        migrations.AddField(
            model_name='partida',
            name='nivel_minimo',
            field=models.CharField(choices=[('Qualquer', 'Qualquer Nível'), ('Iniciante', 'Iniciante e acima'), ('Intermediario', 'Intermediário e acima'), ('Avancado', 'Avançado e acima'), ('Competitivo', 'Apenas Competitivo')], default='Qualquer', max_length=20, verbose_name='Nível Mínimo'),
        ),
    ]
