# Generated by Django 5.2.7 on 2026-04-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0010_rename_partidas_pa_status_9dc607_idx_partidas_pa_status_9b29aa_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='nivel_minimo',
            field=models.CharField(choices=[('Qualquer', 'Qualquer Nível'), ('Iniciante', 'Iniciante'), ('Intermediario', 'Intermediário'), ('Avancado', 'Avançado'), ('Competitivo', 'Competitivo')], default='Qualquer', max_length=20, verbose_name='Nível Mínimo'),
        ),
        migrations.AlterField(
            model_name='partidarsvp',
            name='status',
            field=models.CharField(choices=[('interesse', 'Interesse'), ('aguardando', 'Aguardando Aprovação'), ('confirmado', 'Confirmado'), ('recusado', 'Recusado'), ('expirado', 'Expirado')], default='interesse', max_length=12, verbose_name='Status'),
        ),
    ]
