# Generated by Django 5.2.6 on 2025-09-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Quadra')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_quadras/', verbose_name='Foto da Quadra')),
                ('bairro', models.CharField(choices=[('flamengo', 'Flamengo'), ('centro', 'Centro'), ('sao_jose', 'São José do Imbassaí'), ('itaipuacu', 'Itaipuaçu'), ('itaocaia', 'Itaocaia Valley'), ('parque_nanci', 'Parque Nanci')], max_length=50, verbose_name='Bairro')),
            ],
            options={
                'verbose_name': 'Quadra',
                'verbose_name_plural': 'Quadras',
            },
        ),
    ]
