# Generated by Django 5.2.6 on 2025-09-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadras', '0002_alter_quadra_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadra',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='quadra',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
