# Generated by Django 5.2.6 on 2025-09-18 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadras', '0003_quadra_latitude_quadra_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quadra',
            options={'ordering': ['nome'], 'verbose_name': 'Quadra', 'verbose_name_plural': 'Quadras'},
        ),
        migrations.RemoveField(
            model_name='quadra',
            name='foto',
        ),
        migrations.CreateModel(
            name='FotoQuadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_quadras/', verbose_name='Imagem')),
                ('quadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='quadras.quadra')),
            ],
            options={
                'verbose_name': 'Foto da Quadra',
                'verbose_name_plural': 'Fotos das Quadras',
            },
        ),
    ]
