# Generated by Django 5.2.7 on 2025-11-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadras', '0004_alter_quadra_options_remove_quadra_foto_fotoquadra'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadra',
            name='fonte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte dos dados'),
        ),
        migrations.AlterField(
            model_name='quadra',
            name='bairro',
            field=models.CharField(choices=[('flamengo', 'Flamengo'), ('centro', 'Centro'), ('sao_jose', 'São José do Imbassaí'), ('itaipuacu', 'Itaipuaçu'), ('itaocaia', 'Itaocaia Valley'), ('parque_nanci', 'Parque Nanci'), ('guaratiba', 'Guaratiba'), ('barroco', 'Barroco'), ('caxito', 'Caxito'), ('mumbuca', 'Mumbuca'), ('bananal', 'Bananal'), ('inoã', 'Inoã'), ('itapeba', 'Itapeba')], max_length=50, verbose_name='Bairro'),
        ),
    ]
