# Generated by Django 5.2.6 on 2025-09-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_atividade_options_conversa_mensagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['timestamp']},
        ),
    ]
