# Generated by Django 5.2.6 on 2025-09-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_atividade_options_alter_mensagem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
    ]
