# Generated by Django 5.2.6 on 2025-09-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_atividade_options_alter_mensagem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['timestamp'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
    ]
