# Generated by Django 5.2.6 on 2025-11-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_mensagem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={},
        ),
        migrations.RenameField(
            model_name='conversa',
            old_name='criada_em',
            new_name='criado_em',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='visivel_para_destinatario',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='visivel_para_remetente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
