# Generated by Django 5.2.6 on 2025-11-23 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_mensagem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='conversa',
            options={'ordering': ['-ultima_mensagem_data']},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='conversa',
            name='ultima_mensagem_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
