# Generated by Django 5.2.7 on 2026-03-16 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_atividade_options_alter_conversa_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.atividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_atividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like de Atividade',
                'verbose_name_plural': 'Likes de Atividades',
                'ordering': ['-data_criacao'],
                'unique_together': {('atividade', 'usuario')},
            },
        ),
    ]
