# Generated by Django 5.2.6 on 2026-03-27 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_post_comment_likepost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.comment')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like de Comentário',
                'verbose_name_plural': 'Likes de Comentários',
                'ordering': ['-criado_em'],
                'unique_together': {('comment', 'usuario')},
            },
        ),
    ]
