# Generated by Django 5.2.6 on 2026-03-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_likecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='comentarios/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='conteudo',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
