# Generated by Django 5.2.6 on 2026-03-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_comment_imagem_alter_comment_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gif_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
