# Generated by Django 5.2.6 on 2026-04-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_post_fixado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['criado_em'], 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='fixado',
            field=models.BooleanField(default=False),
        ),
    ]
